Add support for emscripten -- builds (WASM) Use Oniguruma regex library instead of pcreposix on mingw-w64 Add support for static executables and libraries Make libcurl and libssl/libcrypto as optional dependencies Fixed issue in web apps and test suite Resolved XML/JSON serilaization issues [ci skip][docker_compare][skip_build][docker_bench]

diff --git a/.github/workflows/ci-ubuntu.yml b/.github/workflows/ci-ubuntu.yml
--- a/.github/workflows/ci-ubuntu.yml
+++ b/.github/workflows/ci-ubuntu.yml
@@ -63,8 +63,46 @@ jobs:
       run: |
         #sudo su
         #sed -i 's|1.13.1|1.19.1|g' modules/nginx_mod_ffeadcpp/CMakeLists.txt
+        #Shared library version.....
         mkdir build && cd build
-        cmake -GNinja -DSRV_EMB=on -DCINATRA_INCLUDES=/tmp/cinatra/include -DMOD_APACHE=on -DMOD_NGINX=on -DMOD_MEMCACHED=on -DMOD_REDIS=on -DMOD_SDORM_MONGO=on ..
+        cmake -GNinja -DSRV_EMB=on -DMOD_APACHE=on -DMOD_NGINX=on -DMOD_MEMCACHED=on -DMOD_REDIS=on -DMOD_SDORM_MONGO=on ..
+        sudo ninja install
+        cd ../ffead-cpp-5.0-bin
+        sudo chmod 755 *.sh resources/*.sh rtdcf/autotools/*.sh
+        #sudo sed -i'' -e "s|<init>TeBkUmRouter.updateCache</init>||g" web/te-benchmark-um/config/cache.xml
+        #sudo sed -i'' -e "s|<init>TeBkRestController.updateCache</init>||g" web/te-benchmark/config/cache.xml
+        sudo ./server.sh &
+        COUNTER=0
+        while [ ! -f lib/libinter.so ]
+        do
+          sleep 1
+          COUNTER=$((COUNTER+1))
+          if [ "$COUNTER" = 240 ]
+          then
+            echo "ffead-cpp exiting due to failure...."
+            exit 1
+          fi
+        done
+        COUNTER=0
+        while [ ! -f lib/libdinter.so ]
+        do
+          sleep 1
+          COUNTER=$((COUNTER+1))
+          if [ "$COUNTER" = 240 ]
+          then
+            echo "ffead-cpp exiting due to failure....dlib"
+            exit 1
+          fi
+        done
+        echo "ffead-cpp start successful"
+        sleep 5
+        cd tests && sudo chmod +x *.sh tests && sudo ./runTests.sh
+        echo "ffead-cpp normal shutdown"
+        sudo pkill ffead-cpp
+        #Static library version.....
+        cd .. && sudo rm -rf build ffead-cpp-5.0-bin
+        mkdir build && cd build
+        cmake -GNinja -DBUILD_SHARED_LIBS=off -DSRV_EMB=on -DMOD_APACHE=on -DMOD_NGINX=on -DMOD_MEMCACHED=on -DMOD_REDIS=on -DMOD_SDORM_MONGO=on ..
         sudo ninja install
         cd ../ffead-cpp-5.0-bin
         sudo chmod 755 *.sh resources/*.sh rtdcf/autotools/*.sh
@@ -93,17 +131,22 @@ jobs:
             exit 1
           fi
         done
-        echo "normal shutdown"
+        echo "ffead-cpp start successful"
+        sleep 5
+        cd tests && sudo chmod +x *.sh tests && sudo ./runTests.sh
+        echo "ffead-cpp normal shutdown"
         sudo pkill ffead-cpp
+        #With Select event engine .....
         cd .. && sudo rm -rf build ffead-cpp-5.0-bin
         mkdir build && cd build
         cmake -GNinja -DSRV_EMB=on -DMOD_MEMCACHED=on -DMOD_REDIS=on -DMOD_SDORM_MONGO=on -DWITH_SELECT=on ..
         ninja install
+        #With Poll event engine .....
         cd .. && sudo rm -rf build ffead-cpp-5.0-bin
         mkdir build && cd build
         cmake -GNinja -DSRV_EMB=on -DMOD_MEMCACHED=on -DMOD_REDIS=on -DMOD_SDORM_MONGO=on -DWITH_POLL=on ..
         ninja install
-        #With ubuntu 20.04, upgrade kernel to 5.7 and then install liburing
+        #With ubuntu 20.04, upgrade kernel to 5.7 and then install liburing, with io_uring event engine
         #cd /tmp/ 
         #apt install -y kmod linux-base
         #wget -c https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.7/amd64/linux-headers-5.7.0-050700_5.7.0-050700.202006082127_all.deb
